%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: G:\DBilanz\Other\Ali Farooq\RegMethods_Results_08-2020-04\Combined Results JP_v2.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 24-Aug-2020 11:37:58

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 11);

% Specify sheet and range
opts.Sheet     =  "Sheet1";
opts.DataRange =  "A2:K541";

% Specify column names and types
opts.VariableNames = ["FileName", "Outliers", "WKID", "CenterID", "Subregion", "Method", "CtThmm", "wCtThmm", "CtThSDmm", "TVcm", "BMDmgcm"];
opts.SelectedVariableNames = ["FileName", "Outliers", "WKID", "CenterID", "Subregion", "Method", "CtThmm", "wCtThmm", "CtThSDmm", "TVcm", "BMDmgcm"];
opts.VariableTypes = ["categorical", "double", "categorical", "categorical", "categorical", "categorical", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, [1, 3, 4, 5, 6], "EmptyFieldRule", "auto");

% Import the data
CombinedResults = readtable([Folder '\' File], opts, "UseExcel", false);


%% Clear temporary variables
clear opts